theme: jekyll-theme-cayman
markdown: GFM
plugins: []
exclude:
  - "*.yml"
  - "*.yaml"
  - "*.sh"
  - "scripts/"
  - "systemd/"
  - "etc/"
  - "diagrams/"
  - "all/"
  - "LICENSE"
  - "README.md"
  - "INSTALLATION.md"
  - "TROUBLESHOOTING.md"
  - "OVERVIEW.md"
  - ".github/"

